package pe.egcc.eurekaapp.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import pe.egcc.eurekaapp.controller.CuentaController;
import pe.egcc.eurekaapp.db.AccesoDB;
import pe.egcc.eurekaapp.domain.Combo;
import pe.egcc.eurekaapp.util.EurekaUtil;
import pe.egcc.eurekaapp.util.Mensaje;
import pe.egcc.eurekaapp.util.ReportViewInternal;

public class RepoMovimientosView extends javax.swing.JInternalFrame {

  private CuentaController control;
  private boolean estoyOcupado;

  public RepoMovimientosView() {
    initComponents();
    control = new CuentaController();
    estoyOcupado = false;
    llenaCombos();
  }

  private void llenaCombos() {
    estoyOcupado = true;
    EurekaUtil.llenaCombo(cboSucursal, control.getComboSucursales());
    EurekaUtil.llenaCombo(cboCuenta, null);
    lblMoneda.setText("");
    lblSaldo.setText("");
    estoyOcupado = false;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cboSucursal = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    cboCuenta = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    lblMoneda = new javax.swing.JLabel();
    lblSaldo = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    panelReporte = new javax.swing.JPanel();

    setClosable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Criterio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

    jLabel1.setText("Sucursal:");

    cboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cboSucursal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboSucursalActionPerformed(evt);
      }
    });

    jLabel2.setText("Cuenta");

    cboCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cboCuenta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboCuentaActionPerformed(evt);
      }
    });

    jLabel3.setText("Moneda:");

    jLabel4.setText("Saldo:");

    lblMoneda.setText("None");

    lblSaldo.setText("None");

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/reporte-movimientos.png"))); // NOI18N
    jButton1.setText("Ejecutar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(67, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2)
              .addComponent(cboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(lblMoneda)
              .addComponent(lblSaldo))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    panelReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "REPORTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 204, 204))); // NOI18N

    javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
    panelReporte.setLayout(panelReporteLayout);
    panelReporteLayout.setHorizontalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelReporteLayout.setVerticalGroup(
      panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 437, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(panelReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cboSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSucursalActionPerformed
    if (estoyOcupado) {
      return;
    }
    estoyOcupado = true;
    if (cboSucursal.getSelectedIndex() == -1) {
      estoyOcupado = false;
      return;
    }
    try {
      Combo combo = (Combo) cboSucursal.getSelectedItem();
      List<Combo> lstCuentas = control.getComboCuentas(combo.getCodigo());
      EurekaUtil.llenaCombo(cboCuenta, lstCuentas);
      lblMoneda.setText("");
      lblSaldo.setText("");
    } catch (Exception e) {
    }
    estoyOcupado = false;
  }//GEN-LAST:event_cboSucursalActionPerformed

  private void cboCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuentaActionPerformed
    if (estoyOcupado) {
      return;
    }
    estoyOcupado = true;
    lblMoneda.setText("");
    lblSaldo.setText("");
    if (cboCuenta.getSelectedIndex() == -1) {
      estoyOcupado = false;
      return;
    }
    try {
      Combo combo = (Combo) cboCuenta.getSelectedItem();
      Map<String, Object> rec = control.datosCuenta(combo.getCodigo());
      lblMoneda.setText(rec.get("monenombre").toString());
      lblSaldo.setText(rec.get("cuensaldo").toString());
    } catch (Exception e) {
    }
    estoyOcupado = false;
  }//GEN-LAST:event_cboCuentaActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Parámetros
    Combo combo = (Combo) cboCuenta.getSelectedItem();
    if (combo.getCodigo().equals("0")) {
      return;
    }
    Connection cn = null;
    try {
      // Obtener el objeto Connection
      cn = AccesoDB.getConnection();
      // Parametros del reporte
      Map pars = new HashMap();
      pars.put("CUENTA", combo.getCodigo());
      // El reporte
      String fileRepo = "/pe/egcc/eurekaapp/reports/repoMovimientos.jasper";
      InputStream ioRepo = Class.class.getResourceAsStream(fileRepo);
      // Ejecutando el reporte
      JasperPrint jpRepo = JasperFillManager.fillReport(ioRepo, pars, cn);
      // Mostrar el reporte
      //JasperViewer viewer = new JasperViewer(jpRepo, false);
      //viewer.setTitle("Mi Reporte");
      //viewer.setVisible(true);
      
      // Cargando el reporte en el panel
      ReportViewInternal viewer = new ReportViewInternal("MOVIMIENTOS");
      viewer.setReporte(jpRepo);
      viewer.setTitle("MOVIMIENTOS");
      panelReporte.removeAll();
      panelReporte.add(viewer);
      viewer.setVisible(true);
      viewer.setMaximum(true);
      viewer.setClosable(false);
      viewer.setIconifiable(false);
      viewer.setMaximizable(false);
      viewer.setResizable(false);
    } catch (Exception e) {
      Mensaje.showError(rootPane, e.getMessage());
    } finally {
      try {
        cn.close();
      } catch (Exception e) {
      }
    }
  }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> cboCuenta;
  private javax.swing.JComboBox<String> cboSucursal;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblMoneda;
  private javax.swing.JLabel lblSaldo;
  private javax.swing.JPanel panelReporte;
  // End of variables declaration//GEN-END:variables
}
