package pe.egcc.eurekaapp.view;

import javax.swing.JInternalFrame;
import pe.egcc.eurekaapp.domain.Empleado;
import pe.egcc.eurekaapp.util.Memoria;

/**
 *
 * @author Gustavo Coronel
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @github github.com/gcoronelc
 */
public class FormularioMDI extends javax.swing.JFrame {

  public FormularioMDI() {
    initComponents();
    establecerTitulo();
    this.setExtendedState(MAXIMIZED_BOTH);
  }

  private void establecerTitulo() {
    Empleado bean = (Empleado) Memoria.get("usuario");
    String titulo = "EUREKA BANK    [Usuario:" + bean.getUsuario() + "]";
    this.setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    jToolBar1 = new javax.swing.JToolBar();
    btnDeposito = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jSeparator5 = new javax.swing.JToolBar.Separator();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jSeparator6 = new javax.swing.JToolBar.Separator();
    btnArchivoSalir = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    menuArchivoSalir = new javax.swing.JMenuItem();
    menuProceso = new javax.swing.JMenu();
    menuProcesoDeposito = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JPopupMenu.Separator();
    jMenuItem6 = new javax.swing.JMenuItem();
    jMenuItem7 = new javax.swing.JMenuItem();
    menuTabla = new javax.swing.JMenu();
    jMenuItem8 = new javax.swing.JMenuItem();
    jSeparator3 = new javax.swing.JPopupMenu.Separator();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    menuConsulta = new javax.swing.JMenu();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();
    jMenuItem13 = new javax.swing.JMenuItem();
    jSeparator4 = new javax.swing.JPopupMenu.Separator();
    jMenuItem14 = new javax.swing.JMenuItem();
    jMenuItem15 = new javax.swing.JMenuItem();
    menuReporte = new javax.swing.JMenu();
    jMenuItem16 = new javax.swing.JMenuItem();
    jMenuItem17 = new javax.swing.JMenuItem();
    jMenuItem18 = new javax.swing.JMenuItem();
    menuUtil = new javax.swing.JMenu();
    jMenuItem19 = new javax.swing.JMenuItem();
    jMenuItem20 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    btnDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/bank.png"))); // NOI18N
    btnDeposito.setToolTipText("Registrar depósito.");
    btnDeposito.setFocusable(false);
    btnDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnDeposito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnDeposito.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDepositoActionPerformed(evt);
      }
    });
    jToolBar1.add(btnDeposito);

    jButton2.setText("jButton2");
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton2);

    jButton3.setText("jButton3");
    jButton3.setFocusable(false);
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton3);
    jToolBar1.add(jSeparator5);

    jButton4.setText("jButton4");
    jButton4.setFocusable(false);
    jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton4);

    jButton5.setText("jButton5");
    jButton5.setFocusable(false);
    jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton5);
    jToolBar1.add(jSeparator6);

    btnArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/eurekaapp/img/salir.png"))); // NOI18N
    btnArchivoSalir.setToolTipText("Salir del sistema.");
    btnArchivoSalir.setFocusable(false);
    btnArchivoSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnArchivoSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnArchivoSalirActionPerformed(evt);
      }
    });
    jToolBar1.add(btnArchivoSalir);

    menuArchivo.setText("Archivo");

    jMenuItem1.setText("jMenuItem1");
    menuArchivo.add(jMenuItem1);
    menuArchivo.add(jSeparator1);

    menuArchivoSalir.setText("Salir");
    menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuArchivoSalirActionPerformed(evt);
      }
    });
    menuArchivo.add(menuArchivoSalir);

    menuBar.add(menuArchivo);

    menuProceso.setText("Proceso");

    menuProcesoDeposito.setText("Depósito");
    menuProcesoDeposito.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuProcesoDepositoActionPerformed(evt);
      }
    });
    menuProceso.add(menuProcesoDeposito);

    jMenuItem4.setText("jMenuItem4");
    menuProceso.add(jMenuItem4);

    jMenuItem5.setText("jMenuItem5");
    menuProceso.add(jMenuItem5);
    menuProceso.add(jSeparator2);

    jMenuItem6.setText("jMenuItem6");
    menuProceso.add(jMenuItem6);

    jMenuItem7.setText("jMenuItem7");
    menuProceso.add(jMenuItem7);

    menuBar.add(menuProceso);

    menuTabla.setText("Tabla");

    jMenuItem8.setText("jMenuItem8");
    menuTabla.add(jMenuItem8);
    menuTabla.add(jSeparator3);

    jMenuItem9.setText("jMenuItem9");
    menuTabla.add(jMenuItem9);

    jMenuItem10.setText("jMenuItem10");
    menuTabla.add(jMenuItem10);

    menuBar.add(menuTabla);

    menuConsulta.setText("Consulta");

    jMenuItem11.setText("jMenuItem11");
    menuConsulta.add(jMenuItem11);

    jMenuItem12.setText("jMenuItem12");
    menuConsulta.add(jMenuItem12);

    jMenuItem13.setText("jMenuItem13");
    menuConsulta.add(jMenuItem13);
    menuConsulta.add(jSeparator4);

    jMenuItem14.setText("jMenuItem14");
    menuConsulta.add(jMenuItem14);

    jMenuItem15.setText("jMenuItem15");
    menuConsulta.add(jMenuItem15);

    menuBar.add(menuConsulta);

    menuReporte.setText("Reporte");

    jMenuItem16.setText("jMenuItem16");
    menuReporte.add(jMenuItem16);

    jMenuItem17.setText("jMenuItem17");
    menuReporte.add(jMenuItem17);

    jMenuItem18.setText("jMenuItem18");
    menuReporte.add(jMenuItem18);

    menuBar.add(menuReporte);

    menuUtil.setText("Util");

    jMenuItem19.setText("jMenuItem19");
    menuUtil.add(jMenuItem19);

    jMenuItem20.setText("jMenuItem20");
    menuUtil.add(jMenuItem20);

    menuBar.add(menuUtil);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void btnArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnArchivoSalirActionPerformed

  private void menuProcesoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoDepositoActionPerformed
    cargarFormulario(ProcDepositoView.class);
  }//GEN-LAST:event_menuProcesoDepositoActionPerformed

  private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
    cargarFormulario(ProcDepositoView.class);
  }//GEN-LAST:event_btnDepositoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormularioMDI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnArchivoSalir;
  private javax.swing.JButton btnDeposito;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem11;
  private javax.swing.JMenuItem jMenuItem12;
  private javax.swing.JMenuItem jMenuItem13;
  private javax.swing.JMenuItem jMenuItem14;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem17;
  private javax.swing.JMenuItem jMenuItem18;
  private javax.swing.JMenuItem jMenuItem19;
  private javax.swing.JMenuItem jMenuItem20;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JPopupMenu.Separator jSeparator2;
  private javax.swing.JPopupMenu.Separator jSeparator3;
  private javax.swing.JPopupMenu.Separator jSeparator4;
  private javax.swing.JToolBar.Separator jSeparator5;
  private javax.swing.JToolBar.Separator jSeparator6;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenuItem menuArchivoSalir;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuConsulta;
  private javax.swing.JMenu menuProceso;
  private javax.swing.JMenuItem menuProcesoDeposito;
  private javax.swing.JMenu menuReporte;
  private javax.swing.JMenu menuTabla;
  private javax.swing.JMenu menuUtil;
  // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      // Buscar una instancia
      JInternalFrame view = null;
      for (JInternalFrame frame : desktopPane.getAllFrames()) {
        if (aClass.isInstance(frame)) {
          view = frame;
          break;
        }
      }
      // Crear la instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
      }
      // Hacerlo visible
      view.setVisible(true);
      view.setSelected(true);
      view.setMaximum(true);
    } catch (Exception e) {
    }

  }

}
